### ISSUE TITLE
5kmrun.bg app in Huawei App Gallery

### ISSUE THREAD

**Issue by shteryana** [5kmrun-bg/fivekmrun-app#115]
All major/critical features seem to be functioning properly on newer Huawei phones (without Google Services), including

* Past/future events
* Weekly Selfie rating
* Submitting results
* Profile info
* Runner's barcode 

5kmrun.bg app should be available in Huawei App Gallery, so non-technical users using Huawei phones wouldn't need to do `adb install`, etc to use the application

**Comment by etabakov** [comment]
Some resources that might be useful ...

Huawei Developers Portal | Registration:
https://id7.cloud.huawei.com/CAS/portal/loginAuth.html

Join Huawei Developer and Access AppGallery Connect | Video:
https://www.youtube.com/watch?v=ejE3DDdiDcY

**Comment by etabakov** [comment]
- [ ] 📝 Create registration in Huawei Developers Portal
- [ ] 📊 Create a separate configuration for Firebase to track the Huawei app individually
- [ ] 🥇 Upload first version manually
- [ ] 📣 Announce to the community 
- [ ] 🏗️ Create a separate deployment pipeline for Huawei App Gallery

**Comment by etabakov** [comment]
Closing the issue and opening a separate one for the deployment pipeline only.
